<a href="https://colab.research.google.com/github/morojuindu4321/ML_LAB_2026-27/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
list1=[2,3,4,5]
array1=np.array(list1)
print(array1)

[2 3 4 5]


In [ ]:
array1=np.array([2,4,6,8])
print(array1)

[2 4 6 8]


In [ ]:
array1=np.array([[1,2,3,4],
                [5,6,7,8]])
print(array1)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
array1=np.array([[[1,2,3,4],
                 [2,4,6,8],
                [3,6,9,12]],

                [[4,5,6,7],
                 [7,8,9,10],
                 [1,4,8,0]]])
print(array1)

[[[ 1  2  3  4]
  [ 2  4  6  8]
  [ 3  6  9 12]]

 [[ 4  5  6  7]
  [ 7  8  9 10]
  [ 1  4  8  0]]]


In [ ]:
array1=np.array([1,5,2,4])
print(array1.dtype)

int64


In [ ]:
print(array1.ndim)

1


In [ ]:
print(array1.size)

4


In [ ]:
array1=np.array([[2,4,6,8,10],
                 [1,3,5,7,9],
                 [1,1,2,3,5]])
print(array1.shape)

(3, 5)


In [ ]:
array1=np.array([1,2,3,4,5,6])
array2=np.array([12,13,14,15,16,17],dtype=np.int32)
print(array1.itemsize)
print(array2.itemsize)


8
4


In [ ]:
array1=np.array([12,54,76,23])
array2=np.array([[34,26,65],
                 [72,94,69]])
print(array1.data)
print(array2.data)

In [ ]:
array1=np.array([124,234,345,546,384])
print(array1[0])
print(array1[4])
print(array1[2])

124
384
345


In [ ]:
array1[1]=893
print(array1[1])

893


In [ ]:
array1=np.array([[53,78,26],
                 [84,95,67],
                 [22,30,91]])
element1=array1[1][2]
element2=array1[1][0]
print(element1)
print(element2)

67
84


In [ ]:
array1=np.array([8,3,5,2,4])
print(np.median(array1))

4.0


In [ ]:
array1=np.array([78,36,59,62,88])
print(np.mean(array1))

64.6


In [ ]:
print(np.std(array1))


17.79438113562818


In [ ]:
array1=np.array([84,67,48,93])
percent=np.percentile(array1,50)
print(percent)

75.5


In [ ]:
minimum=np.min(array1)
print(minimum)

48


In [ ]:
maximum=np.max(array1)
print(maximum)

93


In [ ]:
x=np.array([[1,2,3],
            [4,5,6]])
y=np.array([7,8,9])
a=np.add(x,y)
print("Addition : \n",a)
b=np.subtract(x,y)
print("Subtraction : \n",b)
c=np.multiply(x,y)
print("Multiplication : \n",c)

Addition : 
 [[ 8 10 12]
 [11 13 15]]
Subtraction : 
 [[-6 -6 -6]
 [-3 -3 -3]]
Multiplication : 
 [[ 7 16 27]
 [28 40 54]]


In [ ]:
array1=np.array([2,4,6,8])
print("Array before appending \n",array1)
newarray=np.append(array1,[1,3,5,7])
print("New Array \n",newarray)
print("Array after appending \n",array1)

Array before appending 
 [2 4 6 8]
New Array 
 [2 4 6 8 1 3 5 7]
Array after appending 
 [2 4 6 8]


In [ ]:
array1 = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)
print("array before appending \n",array1)
newarray = np.append(array1, [[7], [8]], axis=1)
print("new array \n", newarray)
print("array after appending \n", array1)

array before appending 
 [[1 2 3 4]
 [5 6 7 8]]
new array 
 [[1 2 3 4 7]
 [5 6 7 8 8]]
array after appending 
 [[1 2 3 4]
 [5 6 7 8]]


In [ ]:
array1=np.array([61,32,83,74])
np.insert(array1, 1, 56)
np.delete(array1,[1])

array([61, 83, 74])